name: 🚀 Deploy website on push

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js App
        run: npm run build

      - name: Upload to cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.GIT_CPANEL_REACT_SERVER }}
          username: ${{ secrets.GIT_CPANEL_REACT_USER }}
          password: ${{ secrets.GIT_CPANEL_REACT_PWD }}
          protocol: ${{ secrets.GIT_CPANEL_REACT_PROTOCOL }}
          local-dir: ./   # Upload root including .next/
          exclude: |
            **/.git*
            **/node_modules/**
            **/out/**
            **/dist/**
            **/*.md
            **/*.yml
            README*
